;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-buffer
        crux-move-beginning-of-line
        describe-key
        easy-kill
        helm-confirm-and-exit-minibuffer
        iedit-mode
        input-comma-with-space
        kill-region
        undo-tree-or-undo-pp
        ))

(setq mc/cmds-to-run-once
      '(
        comment-dwim
        end-of-buffer
        help-for-help
        iedit-switch-to-mc-mode
        sis--prefix-override-handler
        yas-expand-from-keymap
        ))
