;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        describe-key
        helm-confirm-and-exit-minibuffer
        iedit-mode
        input-comma-with-space
        kill-region
        undo-tree-or-undo-pp
        ))

(setq mc/cmds-to-run-once
      '(
        help-for-help
        iedit-switch-to-mc-mode
        yas-expand-from-keymap
        ))
